version: "3.7"
networks:
  default:
volumes:
  gem_cache:
services:
  db:
    image: mysql:8.0.32-debian
    platform: linux/x86_64
    container_name: app-db
    volumes_from:
      - dbdata
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: referral_app_prod
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - 3306:3306

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-web
    image: referral-app:1.0.0
    volumes:
      - gem_cache:/usr/local/bundle/gems
    networks:
      - default
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    entrypoint: docker-entrypoint.sh
    command: ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      APP_HOST: "https://referral.shreyakurian.com/"
      DOCKER_ENV: "true"
      RAILS_ENV: production
      NODE_ENV: production
      LAUNCHY_DRY_RUN: "true"
      BROWSER: /dev/null
      RAILS_SERVE_STATIC_FILES: true

    depends_on:
      - db
